import { Suspense } from 'react'
import { createBrowserRouter } from 'react-router-dom'
import AppShell, { ProtectedRoute } from '@/components/layout/AppShell.tsx'
import RouteFallback from '@/components/layout/RouteFallback.tsx'
import Login from '@/pages/Login/index.tsx'

// Telas carregadas sob demanda (code-splitting por rota) vêm de `@/lazyPages`.
// O `Suspense` no `AnimatedOutlet` cobre as rotas filhas do AppShell; `Login`,
// `AppShell` e `ProtectedRoute` ficam eager por serem estruturais / a entrada.
import {
  Dashboard, MapPage, Demarcation, BovineRegister, BovineList, BovineDetail,
  DivisionRegister, DivisionList, DivisionDetail, HerdRegister, HerdList, HerdDetail,
  SeasonRegister, SeasonList, SeasonDetail, TroughRegister, TroughList, TroughDetail,
  MedicationRegister, MedicationList, MedicationDetail, FeedRegister, FeedList, FeedDetail,
  ExpenseCategoryRegister, ExpenseCategoryList, ExpenseCategoryDetail,
  SanitaryEventRegister, SanitaryEventList, SanitaryEventDetail,
  TaskRegister, TaskList, TaskDetail, PropertyRegister, PropertyList, PropertyDetail,
  UsersInvitesList, Notifications, ReportsIndex, ExpenseReport, PurchaseReport, SalesReport,
  ApplicationReport, RefillReport, PerformanceReport, InventoryReport,
  ForageRegister, ForageList, ForageDetail, MedicationStockRegister, MedicationStockList,
  FeedStockRegister, FeedStockList, WeighingRegister, SeasonPassageRegister,
  MedicationApplicationRegister, SupplyRegister, SanitaryEventExecution, MembershipRegister,
  BovineTransferRegister, ExpenseRegister, ExpenseList, ExpenseDetail,
  SaleLotRegister, SaleLotList, SaleLotDetail, SaleRegister, SaleList, SaleDetail,
  HerdAllocation, MapBaseConfig, WeighingHistory, ApplicationHistory, RefillHistory,
  AllocationHistory, MembershipHistory, PassageHistory, TransferHistory,
  Profile, Settings, Access, FeedTroughDetail, DevComponents,
} from '@/lazyPages.ts'

export const router = createBrowserRouter([
  {
    path: '/login',
    element: <Login />,
  },
  // Rota de desenvolvimento — fora do AppShell e sem proteção de auth.
  // Suspense próprio porque não passa pelo AnimatedOutlet.
  {
    path: '/dev/components',
    element: (
      <Suspense fallback={<RouteFallback />}>
        <DevComponents />
      </Suspense>
    ),
  },
  {
    element: <ProtectedRoute />,
    children: [
      {
        path: '/',
        element: <AppShell />,
        children: [
          { index: true, element: <Dashboard /> },
          { path: 'map', element: <MapPage /> },
          { path: 'map/offline', element: <MapBaseConfig /> },
          { path: 'demarcation', element: <Demarcation /> },
          { path: 'bovines', element: <BovineList /> },
          { path: 'bovines/new', element: <BovineRegister /> },
          { path: 'bovines/:id', element: <BovineDetail /> },
          { path: 'bovines/:id/edit', element: <BovineRegister /> },
          { path: 'properties', element: <PropertyList /> },
          { path: 'properties/new', element: <PropertyRegister /> },
          { path: 'properties/:id', element: <PropertyDetail /> },
          { path: 'properties/:id/edit', element: <PropertyRegister /> },
          { path: 'users-invites', element: <UsersInvitesList /> },
          { path: 'notifications', element: <Notifications /> },
          { path: 'reports', element: <ReportsIndex /> },
          { path: 'reports/expenses', element: <ExpenseReport /> },
          { path: 'reports/purchases', element: <PurchaseReport /> },
          { path: 'reports/sales', element: <SalesReport /> },
          { path: 'reports/applications', element: <ApplicationReport /> },
          { path: 'reports/refills', element: <RefillReport /> },
          { path: 'reports/performance', element: <PerformanceReport /> },
          { path: 'reports/inventory', element: <InventoryReport /> },
          { path: 'divisions', element: <DivisionList /> },
          { path: 'divisions/new', element: <DivisionRegister /> },
          { path: 'divisions/:id', element: <DivisionDetail /> },
          { path: 'divisions/:id/edit', element: <DivisionRegister /> },
          { path: 'forages', element: <ForageList /> },
          { path: 'forages/new', element: <ForageRegister /> },
          { path: 'forages/:id', element: <ForageDetail /> },
          { path: 'forages/:id/edit', element: <ForageRegister /> },
          { path: 'herds', element: <HerdList /> },
          { path: 'herds/new', element: <HerdRegister /> },
          { path: 'herds/:id', element: <HerdDetail /> },
          { path: 'herds/:id/edit', element: <HerdRegister /> },
          { path: 'seasons', element: <SeasonList /> },
          { path: 'seasons/new', element: <SeasonRegister /> },
          { path: 'seasons/:id', element: <SeasonDetail /> },
          { path: 'seasons/:id/edit', element: <SeasonRegister /> },
          { path: 'troughs', element: <TroughList /> },
          { path: 'troughs/new', element: <TroughRegister /> },
          { path: 'troughs/:id', element: <TroughDetail /> },
          { path: 'troughs/:id/edit', element: <TroughRegister /> },
          { path: 'medications', element: <MedicationList /> },
          { path: 'medications/new', element: <MedicationRegister /> },
          { path: 'medications/:id', element: <MedicationDetail /> },
          { path: 'medications/:id/edit', element: <MedicationRegister /> },
          { path: 'feeds', element: <FeedList /> },
          { path: 'feeds/new', element: <FeedRegister /> },
          { path: 'feeds/:id', element: <FeedDetail /> },
          { path: 'feeds/:id/edit', element: <FeedRegister /> },
          { path: 'expense-categories', element: <ExpenseCategoryList /> },
          { path: 'expense-categories/new', element: <ExpenseCategoryRegister /> },
          { path: 'expense-categories/:id', element: <ExpenseCategoryDetail /> },
          { path: 'expense-categories/:id/edit', element: <ExpenseCategoryRegister /> },
          { path: 'expenses', element: <ExpenseList /> },
          { path: 'expenses/new', element: <ExpenseRegister /> },
          { path: 'expenses/:id', element: <ExpenseDetail /> },
          { path: 'expenses/:id/edit', element: <ExpenseRegister /> },
          { path: 'sale-lots', element: <SaleLotList /> },
          { path: 'sale-lots/new', element: <SaleLotRegister /> },
          { path: 'sale-lots/:id', element: <SaleLotDetail /> },
          { path: 'sales', element: <SaleList /> },
          { path: 'sales/new', element: <SaleRegister /> },
          { path: 'sales/:id', element: <SaleDetail /> },
          { path: 'sanitary-events', element: <SanitaryEventList /> },
          { path: 'sanitary-events/new', element: <SanitaryEventRegister /> },
          { path: 'sanitary-events/:id', element: <SanitaryEventDetail /> },
          { path: 'sanitary-events/:id/edit', element: <SanitaryEventRegister /> },
          { path: 'tasks', element: <TaskList /> },
          { path: 'tasks/new', element: <TaskRegister /> },
          { path: 'tasks/:id', element: <TaskDetail /> },
          { path: 'tasks/:id/edit', element: <TaskRegister /> },
          { path: 'operations/allocation', element: <HerdAllocation /> },
          { path: 'operations/weighing', element: <WeighingRegister /> },
          { path: 'operations/season-passage', element: <SeasonPassageRegister /> },
          { path: 'operations/medication-application', element: <MedicationApplicationRegister /> },
          { path: 'operations/supply', element: <SupplyRegister /> },
          { path: 'operations/sanitary-execution', element: <SanitaryEventExecution /> },
          { path: 'operations/membership', element: <MembershipRegister /> },
          { path: 'operations/bovine-transfer', element: <BovineTransferRegister /> },
          { path: 'history/weighings', element: <WeighingHistory /> },
          { path: 'history/applications', element: <ApplicationHistory /> },
          { path: 'history/refills', element: <RefillHistory /> },
          { path: 'history/allocations', element: <AllocationHistory /> },
          { path: 'history/memberships', element: <MembershipHistory /> },
          { path: 'history/passages', element: <PassageHistory /> },
          { path: 'history/transfers', element: <TransferHistory /> },
          { path: 'medication-stock', element: <MedicationStockList /> },
          { path: 'medication-stock/new', element: <MedicationStockRegister /> },
          { path: 'feed-stock', element: <FeedStockList /> },
          { path: 'feed-stock/new', element: <FeedStockRegister /> },
          { path: 'profile', element: <Profile /> },
          { path: 'settings', element: <Settings /> },
          { path: 'access', element: <Access /> },
          { path: 'feed-troughs/:id', element: <FeedTroughDetail /> },
        ],
      },
    ],
  },
])
